import { VehicleType } from "./types/cars";

export const allVehicles: { [key: string]: VehicleType[] } = {
  Car: [
    {
      VehicleModel: "Camry",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 2,
      options: ["2 Wheel Drive", "Cruise Control", "Gasoline Vehicle"],
    },
    {
      VehicleModel: "Civic",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 2,
      options: ["Sunroof", "Cruise Control"],
    },
    {
      VehicleModel: "Mustang",
      TransmissionType: "Automatic",
      MaxPassengers: 4,
      NumberOfDoors: 2,
      LuggageCapacity: 1,
      options: ["Bluetooth", "Gasoline Vehicle", "AM/FM Radio"],
    },
    {
      VehicleModel: "Accord",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 2,
      options: ["Leather Seats", "Gasoline Vehicle", "Air Conditioner"],
    },
  ],
  Truck: [
    {
      VehicleModel: "F-150",
      TransmissionType: "Automatic",
      MaxPassengers: 6,
      NumberOfDoors: 4,
      LuggageCapacity: 4,
      options: ["2 Wheel Drive", "Cruise Control", "Gasoline Vehicle"],
    },
    {
      VehicleModel: "Silverado",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["Leather Seats", "Air Conditioner", "Gasoline Vehicle"],
    },
    {
      VehicleModel: "Ridgeline",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 4,
      options: ["Leather Seats", "Sunroof", "Air Conditioner"],
    },
    {
      VehicleModel: "Tacoma",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["AM/FM Radio", "2 Wheel Drive", "Bluetooth", "Leather Seats"],
    },
    {
      VehicleModel: "Tundra",
      TransmissionType: "Automatic",
      MaxPassengers: 6,
      NumberOfDoors: 4,
      LuggageCapacity: 4,
      options: ["Gasoline Vehicle", "Cruise Control", "Leather Seats"],
    },
    {
      VehicleModel: "Ranger",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["AM/FM Radio", "Bluetooth", "Air Conditioner"],
    },
  ],
  Van: [
    {
      VehicleModel: "Transit",
      TransmissionType: "Automatic",
      MaxPassengers: 12,
      NumberOfDoors: 5,
      LuggageCapacity: 8,
      options: ["Air Conditioner", "Gasoline Vehicle", "AM/FM Radio"],
    },
    {
      VehicleModel: "Sprinter",
      TransmissionType: "Automatic",
      MaxPassengers: 10,
      NumberOfDoors: 4,
      LuggageCapacity: 6,
      options: ["Air Conditioner", "Bluetooth", "Gasoline Vehicle"],
    },
    {
      VehicleModel: "Odyssey",
      TransmissionType: "Automatic",
      MaxPassengers: 7,
      NumberOfDoors: 4,
      LuggageCapacity: 4,
      options: ["AM/FM Radio", "Air Conditioner", "Sunroof"],
    },
    {
      VehicleModel: "Sienna",
      TransmissionType: "Automatic",
      MaxPassengers: 8,
      NumberOfDoors: 4,
      LuggageCapacity: 4,
      options: ["Cruise Control", "Gasoline Vehicle", "Leather Seats"],
    },
  ],
  SUV: [
    {
      VehicleModel: "CR-V",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["AM/FM Radio", "Air Conditioner", "Bluetooth"],
    },
    {
      VehicleModel: "Pilot",
      TransmissionType: "Automatic",
      MaxPassengers: 8,
      NumberOfDoors: 4,
      LuggageCapacity: 5,
      options: ["Leather Seats", "Gasoline Vehicle", "Cruise Control"],
    },
    {
      VehicleModel: "GL-Class",
      TransmissionType: "Automatic",
      MaxPassengers: 7,
      NumberOfDoors: 4,
      LuggageCapacity: 5,
      options: ["Leather Seats", "Air Conditioner", "Gasoline Vehicle"],
    },
    {
      VehicleModel: "Highlander",
      TransmissionType: "Automatic",
      MaxPassengers: 8,
      NumberOfDoors: 4,
      LuggageCapacity: 5,
      options: ["AM/FM Radio", "Sunroof", "Cruise Control"],
    },
    {
      VehicleModel: "Wrangler",
      TransmissionType: "Manual",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["2 Wheel Drive", "Bluetooth", "AM/FM Radio"],
    },
    {
      VehicleModel: "Cherokee",
      TransmissionType: "Automatic",
      MaxPassengers: 5,
      NumberOfDoors: 4,
      LuggageCapacity: 3,
      options: ["Air Conditioner", "Gasoline Vehicle", "Bluetooth"],
    },
  ],
};
